apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
  namespace: mfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      volumes:
      - name: pvvol
        emptyDir: {}
      containers:
      - image: replace
        name: devsecops-container
        volumeMounts:
        - name: pvvol
          mountPath: /tmp
        securityContext:
           runAsNonRoot: true
           runAsUser: 100
           readOnlyRootFilesystem: true
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
  namespace: mfa
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort